import 'package:flutter/material.dart';
const prefixWeatherIconUrl = 'https://openweathermap.org/img/wn/';
const suffixWeatherIconUrl = '@2x.png';
const weatherApiKey = 'cd9b12b04f5ebd12dcf615d03a5d564e';
const degree = '\u00B0';
const celsius = 'C';
const fahrenheit = 'F';
const String metric = 'metric';
const String imperial = 'imperial';
const cities = ['Athens', 'Berlin', 'Cairo', 'Chittagong', 'Dhaka', 'Jakarta', 'London', 'Los Angeles', 'Moscow', 'New York', 'Sydney', 'Sylhet', 'Tokyo'];
//final backgroundColor = Colors.blue.shade900;
const backgroundColor = Color.fromARGB(255, 18, 18, 61);
const cardBackgroundColor = Color.fromARGB(255, 54, 56, 98);
